id: 14d35b0610f84bce9e3fb7e0400e1276
initial_creation_type: ocr
source_metadata:
  volumes:
    97c7e6f0b5b443d0b2e36f08d109e3a8:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: ''
      total_pages: 1044
      volume_number: 38
